[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info

[INPUT]
    Name    forward
    Listen  0.0.0.0
    Port    24224

[FILTER]
    Name    modify
    Match   *
    Rename  log message

[OUTPUT]
    Name  es
    Match *
    Host  elasticsearch
    Port  9200
    HTTP_User elastic
    HTTP_Passwd ${ELASTIC_PASSWORD}
    Index prepair-api
    Type  _doc
    Retry_Limit 5
    Suppress_Type_Name On